#' From a random forest model generated by caret, generate summary plots
#'
#' @param caret.rf A randomForest model generated by caret
#' @param yvals Feature in the experimental design data frame to use as data labels
#'
#' @return caret.forest.importance A data frame containing variable importance for the random forest model
#' @export
#'
random_forest_summary <- function(caret.rf, yvals){
  # Training summary
  print(caret.rf)
  print(caret.rf$finalModel)
  caret::confusionMatrix(caret.rf)
  # Extract the final forest
  caret.forest <- caret.rf$finalModel
  # Plot the variable importances
  randomForest::varImpPlot(caret.forest)
  # Make the MDSplot
  randomForest::MDSplot(caret.forest, yvals)
  # And the margin plot
  caret.forest.margins <- randomForest::margin(caret.forest,
                                               observed=yvals)
  plot(caret.forest.margins, main='Margin Plot')
  abline(h=0, lty=2)
  #dev.off()
  # Return a data-frame of the selected variables
  caret.forest.importance <- as.data.frame(caret.forest$importance)
  caret.forest.importance$gene <- rownames(caret.forest.importance)
  return(caret.forest.importance)
}
